# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4bviGgq5ZWPlKe2bJde3Cu2kvNHHga7
"""

# Step 1: Install PyPDF2
!pip install PyPDF2

# Step 2: Import required libraries
import os
from PyPDF2 import PdfMerger
from google.colab import drive

# Step 3: Mount Google Drive
drive.mount('/content/drive')

# Step 4: Set the directory containing PDF files
pdf_directory = '/content/drive/My Drive/path_to_your_pdf_folder/'

# Step 5: Initialize PdfMerger object
merger = PdfMerger()

# Step 6: Loop through all PDF files in the directory and merge them
for item in os.listdir(pdf_directory):
    if item.endswith('.pdf'):
        merger.append(os.path.join(pdf_directory, item))

# Step 7: Write out the merged PDF to a file
output_path = '/content/drive/My Drive/path_to_save_merged_pdf/merged.pdf'
merger.write(output_path)
merger.close()

print(f"Merged PDF saved to {output_path}")