# -*- coding: utf-8 -*-
"""PDF text extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psv3R5wqaJDpljfXX9SYot7bV7vONKC9
"""

pip install PyPDF2

from PyPDF2 import PdfReader
import os

# Percorso del PDF
pdf_path = "your/pdf/path/file.pdf"

# Nome del file PDF senza estensione
pdf_filename = os.path.splitext(os.path.basename(pdf_path))[0]

# Crea il percorso del file di testo
output_file_path = f"{pdf_filename}_extracted_text.txt"

# Apre il PDF
pdf_reader = PdfReader(pdf_path)

# Dizionario per contenere il testo di ogni pagina
page_content = {}

# Itera su tutte le pagine del PDF
for page_num in range(len(pdf_reader.pages)):
    # Estrai la pagina corrente
    pdf_page = pdf_reader.pages[page_num]
    # Estrai il testo dalla pagina corrente
    page_text = pdf_page.extract_text()
    # Aggiungi il testo della pagina al dizionario
    page_content[page_num + 1] = page_text

# Scrivi il contenuto di tutte le pagine in un file di testo
with open(output_file_path, "w", encoding="utf-8") as output_file:
    for content in page_content.values():
        output_file.write(content)
        output_file.write("\n\n--- Page Separator ---\n\n")

print(f"Il contenuto è stato salvato in {output_file_path}")