# -*- coding: utf-8 -*-
"""Remove last page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_etIZygf2QQfdvMabZ6SjBCl89sdAR9
"""

!pip install PyMuPDF PyPDF2

from google.colab import drive
drive.mount('/content/drive')

import os
from PyPDF2 import PdfReader, PdfWriter

def process_pdfs(pdf_paths, output_path):
    # Crea un oggetto PdfWriter per il PDF di output
    output_pdf = PdfWriter()

    for pdf_path in pdf_paths:
        # Legge il PDF
        pdf_reader = PdfReader(pdf_path)
        num_pages = len(pdf_reader.pages)

        # Aggiunge tutte le pagine tranne l'ultima al PDF di output
        for i in range(num_pages - 1):
            output_pdf.add_page(pdf_reader.pages[i])

    # Salva il PDF di output
    with open(output_path, 'wb') as output_file:
        output_pdf.write(output_file)
    print(f"PDF combinato salvato in {output_path}")
# Specifica il percorso dei tuoi PDF e il percorso di output
pdf_folder = '/content/drive/MyDrive/AI NEFRO/articoli nefro AI 2024'  # Modifica questo percorso con il percorso della tua cartella PDF
output_pdf_path = '/content/drive/MyDrive/AI NEFRO/articoli nefro AI 2024/FUSED 2024.pdf'  # Modifica questo percorso con il percorso di output desiderato

# Recupera tutti i file PDF nella cartella specificata
pdf_files = [os.path.join(pdf_folder, f) for f in os.listdir(pdf_folder) if f.endswith('.pdf')]

# Processa i PDF
process_pdfs(pdf_files, output_pdf_path)

